### ISSUE TITLE
Potential problem with Buckaroo Banzai

### ISSUE THREAD

**Issue by heasm66** [heasm66/scott2zil#3]
Some sort of "item location bug" in game that the interpreter needs to compensate for.

Game needs a playthrough to see if it is winnable.

**Comment by jpcompton** [comment]
The issue is documented in the ScottKit README:

> The -b (--bug-tolerant) option is needed for Scott Adams Adventure 14b (Buckaroo Banzai), which places one item (the jug of jet fuel) in room 50 of 36.

**Comment by heasm66** [comment]
Played through game to the end. Everything works fine. Closing issue.
