### ISSUE TITLE
Savage Island Part 1 (adv10) starts dark, wrong/extra text

### ISSUE THREAD

**Issue by jpcompton** [heasm66/scott2zil#4]
Savage Island Part 1 starts in the dark and with messages that don't match the actual game welcome banner:

<img width="583" alt="Screen Shot 2020-06-27 at 1 34 51 PM" src="https://user-images.githubusercontent.com/51372049/85929518-2d605e80-b87b-11ea-8745-ef2a2ef8b80c.png">

versus

![Screen Shot 2020-06-27 at 1 35 09 PM](https://user-images.githubusercontent.com/51372049/85929540-4a952d00-b87b-11ea-9792-266af78e9cce.jpg)

Ever so slightly different!

Attaching the base .zil and the output .z5 as well.

[adv10.z5.zip](https://github.com/heasm66/scott2zil/files/4841067/adv10.z5.zip)
[game-dat.zil.zip](https://github.com/heasm66/scott2zil/files/4841070/game-dat.zil.zip)

(update: Lectrote and Gargoyle both <i>do</i> manage to show the Welcome to Adventure 10 banner, but also think that it's sunset and too dark.)

**Comment by heasm66** [comment]
Thanks for the report!

It starts ok in perlscott (where i got the most of the logic from) so hopefully it's a minor thing. I'll look into it.
